/**
 * 辽宁高考历史时间轴数据
 * 基于统编版《中外历史纲要》上下册，结合辽宁高考高频考点
 * 涵盖：中外历史纲要（上）- 中国古代史 + 近代史
 *        中外历史纲要（下）- 世界史
 */

export interface TimelineEvent {
  id: string;
  // 教材定位
  book: '上册' | '下册';
  unit: string;
  lesson?: string;
  // 事件基本信息
  year: number;
  yearEnd?: number;
  title: string;
  // 历史要素
  dynasty?: string;
  location?: string;
  figures?: string[];
  // 详细描述
  summary: string;
  causes?: string;
  effects?: string;
  significance?: string;
  // 高考关联
  examPoints?: string[];
  difficulty?: '高频' | '中频' | '低频';
}

// ============================================================
// 中外历史纲要（上）- 中国古代史部分
// ============================================================

const 上册古代史: TimelineEvent[] = [
  // 第一单元 中华文明起源与早期国家
  {
    id: 'stone-age',
    book: '上册',
    unit: '第一单元 中华文明起源与早期国家',
    year: -10000,
    yearEnd: -2070,
    title: '旧石器时代与新石器时代',
    summary: '人类从打制石器进入磨制石器时代，原始农业和畜牧业产生，氏族公社逐渐形成。',
    effects: '人类开始定居生活，原始宗教和艺术出现。',
    examPoints: ['原始农业', '氏族公社', '仰韶文化', '龙山文化'],
    difficulty: '低频',
  },
  {
    id: 'xia-dynasty',
    book: '上册',
    unit: '第一单元 中华文明起源与早期国家',
    year: -2070,
    yearEnd: -1600,
    title: '夏朝建立',
    dynasty: '夏',
    location: '黄河中下游地区',
    figures: ['大禹', '启'],
    summary: '中国历史上第一个王朝，建立了以王位世袭制为核心的奴隶制国家机器。',
    causes: '原始社会末期生产力发展，私有制和阶级产生。',
    effects: '开创了"家天下"的王位世袭制，中国进入奴隶社会。',
    significance: '早期国家形成的重要标志',
    examPoints: ['王位世袭制', '夏商周更替', '青铜文明'],
    difficulty: '高频',
  },
  {
    id: 'shang-dynasty',
    book: '上册',
    unit: '第一单元 中华文明起源与早期国家',
    year: -1600,
    yearEnd: -1046,
    title: '商朝',
    dynasty: '商',
    location: '黄河中下游，后迁至殷（今安阳）',
    figures: ['商汤', '武丁', '纣王'],
    summary: '商朝是奴隶社会的发展时期，青铜器铸造技术成熟，甲骨文成熟。',
    effects: '甲骨文是目前已知的最早成熟文字；青铜文明达到高峰。',
    significance: '中华文字文明的重要源头',
    examPoints: ['甲骨文', '青铜器', '人祭人殉'],
    difficulty: '中频',
  },
  {
    id: 'zhou-dynasty',
    book: '上册',
    unit: '第一单元 中华文明起源与早期国家',
    year: -1046,
    yearEnd: -256,
    title: '西周与东周',
    dynasty: '周',
    location: '西周都镐京（今西安），东周都洛邑（今洛阳）',
    figures: ['周武王', '周公', '周幽王'],
    summary: '西周实行分封制和宗法制，建立了"礼乐文明"；东周分为春秋和战国两个时期。',
    causes: '周部落强大，灭商建立周朝；分封制巩固统治。',
    effects: '分封制促进各地文化交流，宗法制确立嫡长子继承制，礼乐制度维护等级秩序。',
    significance: '中华礼乐文明传统形成',
    examPoints: ['分封制', '宗法制', '礼乐制度', '春秋战国社会变革'],
    difficulty: '高频',
  },
  // 第二单元 诸侯纷争与社会变革
  {
    id: 'spring-autumn',
    book: '上册',
    unit: '第二单元 诸侯纷争与社会变革',
    year: -770,
    yearEnd: -476,
    title: '春秋时期',
    dynasty: '周（东周）',
    location: '黄河流域各诸侯国',
    figures: ['齐桓公', '晋文公', '管仲', '孔子'],
    summary: '诸侯争霸，周王室衰微；铁器牛耕出现，井田制瓦解；百家争鸣，儒家、道家、法家思想形成。',
    effects: '井田制瓦解，土地私有制出现；生产力发展推动社会变革；思想文化繁荣。',
    significance: '奴隶社会向封建社会过渡的重要时期',
    examPoints: ['铁器牛耕', '井田制瓦解', '诸侯争霸', '百家争鸣', '孔子', '老子'],
    difficulty: '高频',
  },
  {
    id: 'warring-states',
    book: '上册',
    unit: '第二单元 诸侯纷争与社会变革',
    year: -475,
    yearEnd: -221,
    title: '战国时期',
    dynasty: '周（东周）',
    location: '黄河流域至长江流域',
    figures: ['商鞅', '秦孝公', '秦始皇'],
    summary: '战国七雄格局形成，各国变法图强；商鞅变法确立土地私有制，奖励军功，建立县制。',
    effects: '封建土地所有制确立；废除世卿世禄制；建立中央集权的行政制度。',
    significance: '中国封建社会制度的确立',
    examPoints: ['商鞅变法', '封建制度确立', '都江堰', '《诗经》《楚辞》'],
    difficulty: '高频',
  },
  // 第三单元 统一多民族封建国家的建立与巩固
  {
    id: 'qin-unification',
    book: '上册',
    unit: '第三单元 统一多民族封建国家的建立与巩固',
    year: -221,
    yearEnd: -207,
    title: '秦朝统一',
    dynasty: '秦',
    location: '统一六国，定都咸阳',
    figures: ['秦始皇', '李斯'],
    summary: '秦始皇统一六国，建立中国历史上第一个大一统封建王朝；统一文字、货币、度量衡，修筑长城。',
    causes: '商鞅变法后秦国实力增强；各国民众渴望统一。',
    effects: '确立中央集权制度；统一文字货币度量衡；修筑万里长城抵御匈奴。',
    significance: '中国大一统封建国家的开端',
    examPoints: ['中央集权', '郡县制', '统一文字货币', '焚书坑儒', '秦末农民起义'],
    difficulty: '高频',
  },
  {
    id: 'han-dynasty',
    book: '上册',
    unit: '第三单元 统一多民族封建国家的建立与巩固',
    year: -202,
    yearEnd: 220,
    title: '汉朝',
    dynasty: '汉',
    location: '西汉都长安，东汉都洛阳',
    figures: ['刘邦', '汉武帝', '董仲舒', '张骞'],
    summary: '西汉初年休养生息，文景之治；汉武帝"罢黜百家，独尊儒术"，建立察举制度；丝绸之路开通。',
    causes: '秦末战乱后社会凋敝；汉初统治者采取无为而治政策恢复经济。',
    effects: '儒学成为正统思想；丝绸之路促进东西方经济文化交流；造纸术发明。',
    significance: '中华文明的重要奠基时期',
    examPoints: ['文景之治', '汉武帝', '推恩令', '丝绸之路', '罢黜百家', '察举制', '造纸术'],
    difficulty: '高频',
  },
  {
    id: 'han-tribulation',
    book: '上册',
    unit: '第三单元 统一多民族封建国家的建立与巩固',
    year: 184,
    yearEnd: 220,
    title: '黄巾起义与东汉灭亡',
    dynasty: '汉（东汉）',
    location: '全国范围',
    figures: ['张角'],
    summary: '东汉后期政治腐败，土地兼并严重；张角创立太平道，领导黄巾起义；地方势力崛起，最终形成三国鼎立。',
    effects: '东汉中央政府名存实亡；为躲避战乱，人口南迁，江南经济得到开发。',
    significance: '东汉灭亡，三国时代开启',
    examPoints: ['黄巾起义', '三国鼎立', '人口南迁', '江南开发'],
    difficulty: '中频',
  },
  // 第四单元 三国两晋南北朝
  {
    id: 'three-kingdoms',
    book: '上册',
    unit: '第四单元 三国两晋南北朝',
    year: 220,
    yearEnd: 280,
    title: '三国鼎立',
    dynasty: '魏、蜀、吴',
    location: '中国北方、蜀汉（四川）、东吴（江东）',
    figures: ['曹操', '刘备', '孙权', '诸葛亮'],
    summary: '东汉末年群雄割据，曹操统一北方，刘备建立蜀汉，孙权建立东吴，形成三国鼎立局面。',
    effects: '为躲避北方战乱，人口大量南迁，推动江南开发；各国在各自区域内发展经济文化。',
    significance: '为后来西晋统一和南北朝对峙奠定基础',
    examPoints: ['官渡之战', '赤壁之战', '三国鼎立', '人口南迁'],
    difficulty: '中频',
  },
  {
    id: 'western-jin',
    book: '上册',
    unit: '第四单元 三国两晋南北朝',
    year: 280,
    yearEnd: 316,
    title: '西晋统一',
    dynasty: '晋（西晋）',
    location: '统一全国，都洛阳',
    figures: ['司马炎', '司马衷'],
    summary: '司马炎代魏建立西晋，统一全国；但八王之乱导致西晋衰落，北方少数民族入侵。',
    effects: '八王之乱耗尽国力，北方游牧民族内迁，西晋灭亡，北方进入五胡十六国时期。',
    examPoints: ['八王之乱', '五胡内迁'],
    difficulty: '中频',
  },
  {
    id: 'eastern-jin-southern',
    book: '上册',
    unit: '第四单元 三国两晋南北朝',
    year: 317,
    yearEnd: 589,
    title: '东晋与南北朝',
    dynasty: '东晋、宋、齐、梁、陈',
    location: '东晋南渡后都健康（今南京）；北朝经历北魏、东魏、西魏、北齐、北周',
    figures: ['祖逖', '谢安', '孝文帝'],
    summary: '东晋偏安江南；北方五胡十六国更迭，后北魏统一北方；孝文帝改革促进民族融合。',
    effects: '孝文帝汉化改革促进民族融合；江南经济继续发展；南北朝对峙但经济文化交往密切。',
    significance: '民族融合的重要时期，为隋唐统一奠定基础',
    examPoints: ['淝水之战', '孝文帝改革', '江南开发', '民族融合'],
    difficulty: '高频',
  },
  // ============================================================
  // 中外历史纲要（上）- 中国近代史部分
  // ============================================================

  // 第五单元 明清中国版图与文明
  {
    id: 'sui-dynasty',
    book: '上册',
    unit: '第五单元 单元学习之明清',
    year: 581,
    yearEnd: 618,
    title: '隋朝统一',
    dynasty: '隋',
    location: '统一全国，定都长安',
    figures: ['隋文帝', '隋炀帝'],
    summary: '隋文帝杨坚统一南北朝，建立隋朝；隋炀帝开凿大运河，创立科举制度。',
    effects: '大运河加强南北经济文化交流；科举制打破门阀士族垄断，选拔人才；隋朝因暴政而亡。',
    significance: '为唐朝繁荣奠定基础，科举制影响深远',
    examPoints: ['科举制度', '大运河', '三省六部制'],
    difficulty: '高频',
  },
  {
    id: 'tang-dynasty',
    book: '上册',
    unit: '第五单元 单元学习之明清',
    year: 618,
    yearEnd: 907,
    title: '唐朝盛世',
    dynasty: '唐',
    location: '全盛时期版图辽阔，定都长安',
    figures: ['唐太宗', '武则天', '唐玄宗', '李白', '杜甫'],
    summary: '唐朝前期政治清明，经济繁荣，对外开放；贞观之治、开元盛世；诗歌、书法、绘画艺术繁荣。',
    causes: '唐太宗等统治者吸取隋亡教训，轻徭薄赋；均田制保证农民土地；科举制选拔人才。',
    effects: '成为当时世界上最强大的国家；丝绸之路和海上贸易促进中外交流；中华文化圈形成。',
    significance: '中华文明的繁荣时期，对后世影响深远',
    examPoints: ['贞观之治', '开元盛世', '科举制完善', '均田制', '三省六部', '安史之乱', '藩镇割据'],
    difficulty: '高频',
  },
  {
    id: 'song-dynasty',
    book: '上册',
    unit: '第五单元 单元学习之明清',
    year: 960,
    yearEnd: 1279,
    title: '宋元时期',
    dynasty: '宋、元',
    location: '北宋都开封，南宋都杭州；元朝统一全国',
    figures: ['赵匡胤', '王安石', '成吉思汗', '忽必烈'],
    summary: '北宋重文抑武，商业繁荣，儒学复兴；南宋偏安江南；元朝统一，行省制度确立。',
    effects: '商品经济发展，纸币出现；儒学理学化；印刷术、指南针、火药外传；元朝行省制影响后世。',
    significance: '中华文化高度繁荣，民族交融',
    examPoints: ['重文抑武', '王安石变法', '经济重心南移', '行省制度', '理学', '活字印刷', '海上丝绸之路'],
    difficulty: '高频',
  },
  {
    id: 'ming-dynasty',
    book: '上册',
    unit: '第五单元 单元学习之明清',
    year: 1368,
    yearEnd: 1644,
    title: '明朝',
    dynasty: '明',
    location: '明朝全盛版图，定都北京',
    figures: ['朱元璋', '朱棣', '郑和', '张居正'],
    summary: '明朝废除丞相，设内阁；郑和下西洋彰显国威；中后期出现资本主义萌芽；倭寇入侵，明朝衰落。',
    effects: '中央集权强化；郑和下西洋促进中外交流；资本主义萌芽出现；白银流入导致经济危机。',
    significance: '中国封建社会晚期的重要时期',
    examPoints: ['废丞相设内阁', '郑和下西洋', '倭寇', '资本主义萌芽', '一条鞭法', '明朝灭亡原因'],
    difficulty: '高频',
  },
  {
    id: 'qing-dynasty',
    book: '上册',
    unit: '第五单元 单元学习之明清',
    year: 1644,
    yearEnd: 1912,
    title: '清朝',
    dynasty: '清',
    location: '统一的多民族国家，定都北京',
    figures: ['康熙帝', '雍正帝', '乾隆帝'],
    summary: '清朝前期的康乾盛世；疆域奠定，多民族国家统一；文字狱强化专制；后期闭关锁国，鸦片走私严重。',
    effects: '统一多民族国家进一步巩固；人口增长，但人均耕地减少；闭关锁国导致落后于世界潮流。',
    significance: '中国封建社会的最后繁荣与衰落',
    examPoints: ['康乾盛世', '文字狱', '闭关锁国', '疆域奠定', '摊丁入亩', '人口增长', '近代落后的原因'],
    difficulty: '高频',
  },
];

// ============================================================
// 中外历史纲要（下）- 世界史部分
// ============================================================

const 下册世界史: TimelineEvent[] = [
  // 第一单元 古代世界文明
  {
    id: 'ancient-egypt',
    book: '下册',
    unit: '第一单元 古代世界文明',
    year: -3500,
    yearEnd: -30,
    title: '古埃及文明',
    location: '尼罗河流域',
    summary: '古埃及是世界上最早的文明之一，金字塔是典型代表，使用象形文字，制定太阳历。',
    effects: '为人类文明发展奠定基础；金字塔成为世界奇迹。',
    examPoints: ['金字塔', '象形文字', '太阳历'],
    difficulty: '低频',
  },
  {
    id: 'ancient-mesopotamia',
    book: '下册',
    unit: '第一单元 古代世界文明',
    year: -3500,
    yearEnd: -539,
    title: '两河流域文明',
    location: '两河流域（幼发拉底河、底格里斯河）',
    summary: '苏美尔人创造楔形文字，颁布《汉谟拉比法典》；空中花园是世界奇迹之一。',
    examPoints: ['楔形文字', '《汉谟拉比法典》', '空中花园'],
    difficulty: '低频',
  },
  {
    id: 'ancient-greece',
    book: '下册',
    unit: '第一单元 古代世界文明',
    year: -2000,
    yearEnd: -146,
    title: '古希腊罗马文明',
    location: '希腊半岛、爱琴海地区、意大利',
    figures: ['伯里克利', '苏格拉底', '柏拉图', '亚里士多德'],
    summary: '古希腊创造了辉煌的城邦民主制度，哲学、文学、艺术高度发达；古罗马继承并发展了希腊文化，建立帝国。',
    effects: '奠定西方文明基础；民主制度、哲学思想影响深远。',
    examPoints: ['城邦制度', '伯里克利改革', '苏格拉底柏拉图亚里士多德', '罗马法', '公民大会'],
    difficulty: '高频',
  },
  // 第二单元 走向近代
  {
    id: 'renaissance',
    book: '下册',
    unit: '第二单元 走向近代',
    year: 1300,
    yearEnd: 1600,
    title: '文艺复兴',
    location: '意大利，后传播至欧洲',
    figures: ['但丁', '达芬奇', '莎士比亚'],
    summary: '文艺复兴是欧洲思想文化运动，以人文主义为核心，反对神学权威，提倡人性解放。',
    effects: '促进思想解放；推动科学革命；为资本主义发展提供精神动力。',
    significance: '欧洲近代史的开端',
    examPoints: ['人文主义', '宗教改革', '但丁', '达芬奇', '莎士比亚'],
    difficulty: '高频',
  },
  {
    id: 'protestant-reformation',
    book: '下册',
    unit: '第二单元 走向近代',
    year: 1517,
    yearEnd: 1648,
    title: '宗教改革',
    location: '德意志，后扩展至欧洲',
    figures: ['马丁·路德', '加尔文'],
    summary: '马丁·路德发表《九十五条论纲》，反对教皇出售赎罪券；新教形成，天主教会分裂。',
    effects: '打破天主教会权威；促进民族国家形成；推动资本主义发展。',
    examPoints: ['马丁·路德', '《九十五条论纲》', '新教', '加尔文'],
    difficulty: '中频',
  },
  {
    id: 'geographic-discovery',
    book: '下册',
    unit: '第二单元 走向近代',
    year: 1488,
    yearEnd: 1522,
    title: '新航路开辟',
    location: '欧洲→美洲、亚洲、非洲',
    figures: ['哥伦布', '达伽马', '麦哲伦'],
    summary: '哥伦布发现美洲，达伽马到达印度，麦哲伦完成环球航行，世界市场开始形成。',
    causes: '奥斯曼帝国阻断传统商路；欧洲商品经济发展需求；航海技术进步。',
    effects: '世界市场雏形出现；殖民掠夺开始；物种交流与"三角贸易"；欧洲中心地位确立。',
    significance: '世界联为一体，殖民时代开启',
    examPoints: ['哥伦布', '达伽马', '麦哲伦', '世界市场', '三角贸易', '殖民扩张'],
    difficulty: '高频',
  },
  {
    id: 'english-bill',
    book: '下册',
    unit: '第二单元 走向近代',
    year: 1689,
    title: '英国《权利法案》',
    location: '英国',
    summary: '英国议会通过《权利法案》，确立君主立宪制，限制王权，保障议会权力。',
    effects: '英国确立君主立宪制；为其他国家提供政治制度借鉴。',
    significance: '英国君主立宪制确立',
    examPoints: ['君主立宪制', '《权利法案》', '光荣革命'],
    difficulty: '高频',
  },
  {
    id: 'american-revolution',
    book: '下册',
    unit: '第二单元 走向近代',
    year: 1776,
    yearEnd: 1783,
    title: '美国独立战争',
    location: '北美十三殖民地',
    figures: ['华盛顿', '杰斐逊'],
    summary: '北美殖民地人民在启蒙思想影响下，发表《独立宣言》，建立美利坚合众国。',
    effects: '美国建立联邦制共和国；颁布《1787年宪法》；开创三权分立先例。',
    significance: '美洲第一个独立国家',
    examPoints: ['《独立宣言》', '华盛顿', '《1787年宪法》', '三权分立'],
    difficulty: '高频',
  },
  {
    id: 'french-revolution',
    book: '下册',
    unit: '第二单元 走向近代',
    year: 1789,
    yearEnd: 1815,
    title: '法国大革命',
    location: '法国',
    figures: ['罗伯斯庇尔', '拿破仑'],
    summary: '法国人民攻占巴士底狱，颁布《人权宣言》，处死国王，建立法兰西第一共和国；拿破仑建立帝国。',
    effects: '传播自由平等思想；打击欧洲封建势力；拿破仑法典影响深远。',
    significance: '震撼欧洲的革命',
    examPoints: ['巴士底狱', '《人权宣言》', '《拿破仑法典》', '自由平等博爱'],
    difficulty: '高频',
  },
  {
    id: 'industrial-revolution',
    book: '下册',
    unit: '第二单元 走向近代',
    year: 1760,
    yearEnd: 1840,
    title: '工业革命',
    location: '英国，后传播至欧美',
    figures: ['瓦特', '哈格里夫斯'],
    summary: '工业革命从英国棉纺织业开始，蒸汽机广泛应用，机器生产取代手工劳动。',
    effects: '社会生产力飞速发展；城市化进程加快；工人阶级形成；列强加紧殖民扩张。',
    significance: '人类进入工业时代',
    examPoints: ['珍妮纺纱机', '瓦特蒸汽机', '工厂制度', '工业革命影响', '马克思主义诞生'],
    difficulty: '高频',
  },
  // 第三单元 工业革命与资本主义发展
  {
    id: 'american-civil-war',
    book: '下册',
    unit: '第三单元 工业革命与资本主义发展',
    year: 1861,
    yearEnd: 1865,
    title: '美国内战（南北战争）',
    location: '美国',
    figures: ['林肯'],
    summary: '美国南方与北方因奴隶制问题爆发战争，林肯领导北方获胜，废除奴隶制。',
    effects: '美国废除奴隶制，维护国家统一；为资本主义发展扫清障碍。',
    significance: '美国历史上的重要转折',
    examPoints: ['林肯', '《解放宣言》', '废除奴隶制', '南北矛盾'],
    difficulty: '高频',
  },
  {
    id: 'meiji-restoration',
    book: '下册',
    unit: '第三单元 工业革命与资本主义发展',
    year: 1868,
    title: '日本明治维新',
    location: '日本',
    summary: '日本倒幕派推翻幕府统治，天皇重新掌权，实施明治维新，全面学习西方。',
    effects: '日本迅速走上资本主义道路；成为亚洲强国；但保留军国主义残余。',
    significance: '日本近代化的开端',
    examPoints: ['明治维新', '殖产兴业', '文明开化', '富国强兵', '日本崛起'],
    difficulty: '高频',
  },
  {
    id: 'second-industrial',
    book: '下册',
    unit: '第三单元 工业革命与资本主义发展',
    year: 1870,
    yearEnd: 1914,
    title: '第二次工业革命',
    location: '欧美主要资本主义国家',
    figures: ['爱迪生', '西门子'],
    summary: '电力和内燃机广泛应用，石油、化学工业兴起，垄断组织形成，主要资本主义国家进入帝国主义阶段。',
    effects: '生产效率大幅提高；垄断组织出现；资本主义经济危机周期性爆发；列强瓜分世界。',
    significance: '人类进入电气时代',
    examPoints: ['电力革命', '内燃机', '垄断组织', '帝国主义', '瓜分世界'],
    difficulty: '高频',
  },
  // 第四单元 两次世界大战
  {
    id: 'ww1',
    book: '下册',
    unit: '第四单元 两次世界大战',
    year: 1914,
    yearEnd: 1918,
    title: '第一次世界大战',
    location: '欧洲为主',
    figures: ['萨拉热窝事件'],
    summary: '欧洲两大军事集团（同盟国与协约国）因萨拉热窝事件爆发战争，战场上使用机枪、毒气、坦克等新式武器。',
    causes: '帝国主义政治经济发展不平衡；同盟国与协约国两大军事集团对峙；民族主义情绪高涨。',
    effects: '欧洲列强削弱；俄国十月革命爆发；美国、日本崛起；凡尔赛-华盛顿体系建立。',
    significance: '人类历史上的空前浩劫',
    examPoints: ['萨拉热窝事件', '同盟国协约国', '凡尔赛和约', '《九国公约》'],
    difficulty: '高频',
  },
  {
    id: 'russian-revolution',
    book: '下册',
    unit: '第四单元 两次世界大战',
    year: 1917,
    title: '俄国十月革命',
    location: '俄国',
    figures: ['列宁'],
    summary: '布尔什维克党在列宁领导下发动十月革命，建立世界上第一个社会主义国家。',
    effects: '打破资本主义一统天下的局面；为各国无产阶级革命提供借鉴；苏联建立计划经济体制。',
    significance: '人类历史新纪元',
    examPoints: ['十月革命', '列宁', '苏维埃政权', '社会主义'],
    difficulty: '高频',
  },
  {
    id: 'ww2',
    book: '下册',
    unit: '第四单元 两次世界大战',
    year: 1939,
    yearEnd: 1945,
    title: '第二次世界大战',
    location: '欧洲、亚洲、非洲、太平洋',
    figures: ['希特勒', '罗斯福', '丘吉尔', '斯大林'],
    summary: '法西斯国家发动侵略战争，中国、苏联、美国、英国等组成反法西斯同盟，最终取得胜利。',
    causes: '1929年经济大危机；法西斯主义抬头；凡尔赛-华盛顿体系埋下祸根。',
    effects: '法西斯政权覆灭；联合国成立；两极格局形成；亚非拉民族解放运动高涨。',
    significance: '人类历史上规模最大的战争',
    examPoints: ['法西斯侵略', '绥靖政策', '珍珠港', '诺曼底登陆', '雅尔塔体系', '联合国'],
    difficulty: '高频',
  },
  // 第五单元 冷战与当代国际格局
  {
    id: 'cold-war',
    book: '下册',
    unit: '第五单元 冷战与当代国际格局',
    year: 1947,
    yearEnd: 1991,
    title: '冷战',
    location: '全球',
    figures: ['杜鲁门', '丘吉尔', '赫鲁晓夫'],
    summary: '二战后美苏两国在政治、经济、军事方面对峙，形成资本主义与社会主义两大阵营的全面冷战。',
    effects: '欧洲分裂为东西两部分；柏林墙修建；古巴导弹危机；两极格局最终在1991年瓦解。',
    significance: '20世纪后半叶国际关系的主要特征',
    examPoints: ['杜鲁门主义', '马歇尔计划', '北约', '华约', '柏林墙', '古巴导弹危机', '两极格局'],
    difficulty: '高频',
  },
  {
    id: 'eu-integration',
    book: '下册',
    unit: '第五单元 冷战与当代国际格局',
    year: 1957,
    yearEnd: 1993,
    title: '欧洲一体化进程',
    location: '西欧',
    summary: '从欧洲煤钢联营到欧洲共同体，再到1993年欧盟成立，欧洲一体化不断深化。',
    effects: '促进欧洲和平与发展；提高欧洲国际地位；为区域合作提供模式。',
    examPoints: ['欧共体', '欧盟', '欧洲一体化'],
    difficulty: '中频',
  },
  {
    id: 'ussr-collapse',
    book: '下册',
    unit: '第五单元 冷战与当代国际格局',
    year: 1991,
    title: '苏联解体',
    location: '苏联',
    summary: '苏联在政治经济危机中解体，十五个独立国家诞生，两极格局终结。',
    effects: '两极格局瓦解；世界多极化趋势加强；国际格局进入转型期。',
    significance: '20世纪最重要的历史事件之一',
    examPoints: ['苏联解体', '两极格局终结', '多极化趋势'],
    difficulty: '高频',
  },
  // 第六单元 现代世界与全球化
  {
    id: 'new-tech-revolution',
    book: '下册',
    unit: '第六单元 现代世界与全球化',
    year: 1945,
    yearEnd: 2000,
    title: '第三次科技革命',
    location: '全球',
    figures: ['计算机之父冯·诺依曼'],
    summary: '计算机、原子能、航天技术、生物工程等飞速发展，人类进入信息时代和知识经济时代。',
    effects: '产业结构深刻变化；知识经济兴起；全球化加速；国际竞争转向科技和人才竞争。',
    significance: '人类进入信息时代',
    examPoints: ['计算机', '互联网', '第三次科技革命', '知识经济'],
    difficulty: '高频',
  },
  {
    id: 'globalization',
    book: '下册',
    unit: '第六单元 现代世界与全球化',
    year: 1990,
    yearEnd: 2020,
    title: '经济全球化',
    location: '全球',
    summary: '冷战结束后，经济全球化加速发展，跨国公司、WTO、世界银行、国际货币基金组织发挥重要作用。',
    effects: '世界联系日益紧密；发展中国家机遇与挑战并存；逆全球化现象出现。',
    examPoints: ['经济全球化', 'WTO', '跨国公司', '命运共同体', '逆全球化'],
    difficulty: '高频',
  },
  // ============================================================
  // 中国近代史（纲要下册相关内容）
  // ============================================================
  {
    id: 'opium-war',
    book: '下册',
    unit: '第二学习主题 中国近代史',
    year: 1840,
    yearEnd: 1842,
    title: '鸦片战争',
    location: '中国东南沿海',
    figures: ['林则徐', '道光皇帝'],
    summary: '英国为打开中国市场、倾销鸦片，发动侵略战争；清政府战败，签订《南京条约》。',
    causes: '英国工业革命后急需原料产地和商品市场；清朝闭关锁国贸易逆差；鸦片走私危害严重。',
    effects: '中国开始沦为半殖民地半封建社会；五口通商；协定关税；领事裁判权。',
    significance: '中国近代史开端',
    examPoints: ['《南京条约》', '半殖民地半封建社会', '近代史开端'],
    difficulty: '高频',
  },
  {
    id: 'sino-japanese-war',
    book: '下册',
    unit: '第二学习主题 中国近代史',
    year: 1894,
    yearEnd: 1895,
    title: '甲午中日战争',
    location: '朝鲜半岛、黄海、辽东',
    figures: ['邓世昌', '李鸿章'],
    summary: '日本明治维新后走上扩张道路，发动侵华战争；北洋水师全军覆没，清政府被迫签订《马关条约》。',
    causes: '日本明治维新后对外扩张；朝鲜东学党起义；列强纵容。',
    effects: '《马关条约》割让台湾、辽东半岛（后赎回）；赔款2亿两白银；开放沙市、重庆等；允许设厂。',
    significance: '中国半殖民地化程度大大加深',
    examPoints: ['《马关条约》', '台湾割让', '列强瓜分中国', '民族危机加深'],
    difficulty: '高频',
  },
  {
    id: 'eight-nation-alliance',
    book: '下册',
    unit: '第二学习主题 中国近代史',
    year: 1900,
    yearEnd: 1901,
    title: '八国联军侵华',
    location: '北京及华北地区',
    summary: '义和团运动兴起后，八国联军以"镇压义和团"为名侵略中国，攻占北京，慈禧太后西逃。',
    effects: '签订《辛丑条约》，中国完全沦为半殖民地；赔款4.5亿两白银；拆除大沽炮台；禁止反帝。',
    significance: '中国半殖民地半封建社会完全形成',
    examPoints: ['《辛丑条约》', '完全沦为半殖民地', '清政府成为列强工具'],
    difficulty: '高频',
  },
  {
    id: 'xinhai-revolution',
    book: '下册',
    unit: '第二学习主题 中国近代史',
    year: 1911,
    yearEnd: 1912,
    title: '辛亥革命',
    location: '武昌',
    figures: ['孙中山', '黄兴'],
    summary: '同盟会多次武装起义，武昌起义成功；中华民国成立，清朝覆亡。',
    effects: '推翻了两千多年的封建君主专制制度；建立资产阶级共和国；颁布《临时约法》。',
    significance: '中国近代史上第一次完全意义上的民族民主革命',
    examPoints: ['武昌起义', '中华民国', '《临时约法》', '辛亥革命意义'],
    difficulty: '高频',
  },
  {
    id: 'may-fourth-movement',
    book: '下册',
    unit: '第二学习主题 中国近代史',
    year: 1919,
    title: '五四运动',
    location: '北京、上海',
    figures: ['陈独秀', '李大钊'],
    summary: '巴黎和会拒绝中国合理要求，北京学生示威游行；工人阶级登上政治舞台。',
    effects: '马克思主义在中国传播；新民主主义革命开端；为中国共产党的成立奠定基础。',
    significance: '中国新民主主义革命的开端',
    examPoints: ['新民主主义革命开端', '马克思主义传播', '工人阶级登上舞台'],
    difficulty: '高频',
  },
  {
    id: 'cppc-founding',
    book: '下册',
    unit: '第二学习主题 中国近代史',
    year: 1921,
    title: '中国共产党成立',
    location: '上海（后转移至嘉兴南湖）',
    figures: ['毛泽东', '董必武', '陈独秀'],
    summary: '在马克思主义与中国工人运动结合的基础上，中国共产党第一次全国代表大会召开。',
    effects: '中国革命面貌焕然一新；国共合作推动国民革命；为民族解放指明方向。',
    significance: '中国革命的面貌从此焕然一新',
    examPoints: ['中共一大', '马克思主义', '中国革命面貌'],
    difficulty: '高频',
  },
  {
    id: 'nantianmen-square',
    book: '下册',
    unit: '第二学习主题 中国近代史',
    year: 1949,
    title: '中华人民共和国成立',
    location: '北京天安门',
    figures: ['毛泽东', '周恩来'],
    summary: '毛泽东在天安门城楼庄严宣告中华人民共和国中央人民政府成立。',
    effects: '中国结束半殖民地半封建社会；开辟中国历史新纪元；人民当家作主。',
    significance: '中国历史新纪元',
    examPoints: ['新中国成立', '半殖民地半封建社会结束', '人民当家作主'],
    difficulty: '高频',
  },
  {
    id: 'reform-opening',
    book: '下册',
    unit: '第二学习主题 中国近代史',
    year: 1978,
    title: '改革开放',
    location: '中国',
    figures: ['邓小平'],
    summary: '中共十一届三中全会确立改革开放方针；农村家庭联产承包责任制；城市企业改革；设立经济特区。',
    effects: '中国经济的快速发展；综合国力显著增强；人民生活水平大幅提高；中国日益走向世界舞台中心。',
    significance: '中华民族伟大复兴的里程碑',
    examPoints: ['十一届三中全会', '改革开放', '经济特区', '家庭联产承包', '中国特色社会主义'],
    difficulty: '高频',
  },
];

// 合并所有数据
export const historyTimelineData: TimelineEvent[] = [...上册古代史, ...下册世界史];

// 按年代排序
historyTimelineData.sort((a, b) => a.year - b.year);

// 按单元分组
export const unitGroups = historyTimelineData.reduce<Record<string, TimelineEvent[]>>((acc, event) => {
  if (!acc[event.unit]) {
    acc[event.unit] = [];
  }
  acc[event.unit].push(event);
  return acc;
}, {});

// 获取高频考点事件
export const highFrequencyEvents = historyTimelineData.filter(e => e.difficulty === '高频');

// 搜索功能
export function searchEvents(keyword: string): TimelineEvent[] {
  const lower = keyword.toLowerCase();
  return historyTimelineData.filter(e =>
    e.title.toLowerCase().includes(lower) ||
    e.summary.toLowerCase().includes(lower) ||
    e.unit.toLowerCase().includes(lower) ||
    e.examPoints?.some(p => p.toLowerCase().includes(lower)) ||
    e.figures?.some(f => f.toLowerCase().includes(lower))
  );
}

// 获取指定年代范围的事件
export function getEventsByYearRange(start: number, end: number): TimelineEvent[] {
  return historyTimelineData.filter(e =>
    (e.year >= start && e.year <= end) ||
    (e.yearEnd && e.yearEnd >= start && e.yearEnd <= end)
  );
}
